- id: validate-schema
  name: Validate Schema datasets
  description: Validate Amsterdam Schema dataset files
  entry: schema batch-validate
  language: python
  types: ["json"]
- id: validate-publishers
  name: Validate Schema publishers
  description: Validate Amsterdam Schema publisher files
  entry: schema validate-publishers
  language: python
  exclude: ^.*$ # prevent passing any files
  always_run: true
- id: validate-scopes
  name: Validate Schema publishers
  description: Validate Amsterdam Schema scope files
  entry: schema validate-scopes
  language: python
  exclude: ^.*$ # prevent passing any files
  always_run: true
