# File format: https://pre-commit.com/#plugins
# Supported hooks: https://pre-commit.com/hooks.html
# Running "make format" fixes most issues for you
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        additional_dependencies:
          - click==8.0.2  # Pin click, latest version is missing `_unicodefun` needed by black
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--quiet, --exclude, tests]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: migrations/
        additional_dependencies:
          - flake8-colors  # ANSI colors highlight for Flake8
          - flake8-raise  # Find improvements for raise statements
          - flake8-bandit  # Security checks
          - flake8-comprehensions # Write better list/set/dict comprehensions.
          - flake8-implicit-str-concat  #
          - flake8-rst  # Allows run flake8 on code snippets in docstrings or rst files
          - flake8-string-format  # str.format checker
          - flake8-logging-format  # Validate logging format strings
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json  # Checks json files for parseable syntax
      - id: check-merge-conflict  # Check for files that contain merge conflict strings
      - id: check-toml  # Checks toml files for parseable syntax
      - id: check-yaml  # Checks yaml files for parseable syntax
      - id: debug-statements  # Check for debugger imports and py37+ `breakpoint()` calls
      - id: detect-private-key  # Detects the presence of private keys
      - id: end-of-file-fixer  # Ensures that a file is either empty, or ends with one newline
      - id: trailing-whitespace  # trims trailing whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-docstring-first  # Checks a common error of defining a docstring after code
  -   repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0  # Use the ref you want to point at
      hooks:
        - id: python-check-blanket-noqa  # Enforce that noqa annotations always occur with specific codes
        - id: python-no-eval  # A quick check for the eval() built-in function
        - id: python-no-log-warn  # A quick check for the deprecated .warn() method of python loggers
        - id: rst-backticks  # Detect common mistake of using single backticks when writing rst
        - id: rst-directive-colons  # Detect mistake of rst directive not ending with double colon
        - id: rst-inline-touching-normal  # Detect mistake of inline code touching normal text in rst
