# This compose file is supplied for local dev
# Since there is no running process, it just starts a bash
# session in order to run tests etc.
version: "3.0"
services:
  database:
    image: postgis/postgis:14-3.2
    ports:
      - "5417:5432"
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: dataservices
      POSTGRES_PASSWORD: insecure

  app:
    build: .
    links:
      - database
    environment:
      SECRET_KEY: insecure
      # In order to use local datasets
      SCHEMA_URL: /tmp/ams-schema/datasets
      DATABASE_URL: "postgresql://dataservices:insecure@database/dataservices"
    env_file: .env
    volumes:
      - ".:/app"
    command: >
      bash
