# This compose file is supplied for local dev tests to spin up a postgres container with postgis
services:
  database:
    image: postgis/postgis:14-3.2
    ports:
      - "5417:5432"
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: dataservices
      POSTGRES_PASSWORD: insecure
