# This compose file is supplied for local testrunning.
version: "3.7"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5415:5432"
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: dataservices
      POSTGRES_PASSWORD: insecure
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 3s

  tests:
    build: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      SECRET_KEY: insecure
      # In order to use local datasets
      SCHEMA_URL: /app/ams-schema/datasets
      DATABASE_URL: "postgresql://dataservices:insecure@database/dataservices"
    env_file: .env
