version: "3.7"
services:
  web:
    network_mode: host
    build:
      context: .
    environment:
      DATABASE_URL: "postgres://dataservices:insecure@${HOSTNAME}:5416/dataservices"
      SCHEMA_URL: https://356c76835e424b968ed6d654c51204f0.objectstore.eu/schemas-development/datasets/
      BOOTSTRAP_SERVERS: ${HOSTNAME}:29092
      TOPIC: events
      GROUP_ID: python_jan_example_group_1
      AUTO_OFFSET_RESET: earliest

      # command: uwsgi --py-auto-reload=1
