# Generated by Django 3.0.7 on 2021-03-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0009_auto_20210324_1157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasettable",
            name="db_table",
            field=models.CharField(max_length=100),
        ),
    ]
