# Generated by Django 5.2.5 on 2025-09-25 13:41
from __future__ import annotations

from django.db import migrations, models

import schematools.contrib.django.validators


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0023_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "schema_data",
                    models.TextField(
                        validators=[schematools.contrib.django.validators.validate_json],
                        verbose_name="Amsterdam Schema Contents",
                    ),
                ),
            ],
        ),
    ]
