# Generated by Django 5.2.17 on 2026-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0028_dataset_delete_date_datasettable_delete_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("D", "under_development"),
                    ("S", "stable"),
                    ("U", "superseded"),
                    ("X", "deprecated"),
                    ("F", "discontinued"),
                ],
                default="D",
            ),
        ),
    ]
