version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: dataservices
      POSTGRES_PASSWORD: insecure

  test:
    build: ../
    links:
      - database
    environment:
      SECRET_KEY: insecure
      SCHEMA_URL: https://schemas.data.amsterdam.nl/datasets/
      DATABASE_URL: "postgres://dataservices:insecure@database/dataservices"
    command: >
      bash -c ".jenkins/test.sh"
