# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: insecure
          POSTGRES_DB: dataservices_test
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-add-repository "ppa:ubuntugis/ubuntugis-unstable"
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        pip install GDAL==3.0.4
        python -m pip install --upgrade pip
        pip install -e .[tests,django]
    - name: Test with pytest
      run: |
        pytest tests
